language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
#  - composer self-update  # commented out as it crashes often
  - composer install --prefer-source --no-interaction --dev

script: phpunit
